### ISSUE TITLE
[CSharp] Apostila CSharp e Orientação a Objetos Alura

### ISSUE THREAD

**Issue by AlvesMarcosA** [SilasRodrigues19/ProgrammingBooks#7]
[apostila-csharp-orientacao-objetos.pdf](https://github.com/SilasRodrigues19/ProgrammingBooks/files/11227294/apostila-csharp-orientacao-objetos.pdf)

- C#
- POO

**Comment by SilasRodrigues19** [comment]
@AlvesMarcosA  Vou editar pra "C#" que é o nome original da label

Adicionei prefixos que deveriam funcionar, mas por algum motivo o actions está usando o arquivo antes da alteração

Esse é o arquivo atual com mais opções em `labels-synonyms`:
```yml
name: Labeling new issue
on:
  issues:
    types: ['opened', 'edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.PDF_ISSUE_TOKEN }}
          labels-synonyms: '{"CSS":["SASS","LESS","Bootstrap", "Tailwind", "Material UI", "Chakra UI"],"JavaScript":["TypeScript", "React", "ReactJS", "VueJS", "Angular", "Svelte"], "C#":["CSharp", "C Sharp", "C-Sharp"]}'
          labels-not-allowed: '["Falta de informações"]'
          default-labels: '["PDF"]'
```

O actions está usando esse, ainda não sei porque:

```yml
name: Labeling new issue
on:
  issues:
    types: ['opened', 'edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.PDF_ISSUE_TOKEN }}
          labels-synonyms: '{"CSS":["SASS","LESS","Bootstrap", "Tailwind", "Material UI", "Chakra UI"],"JavaScript":["TypeScript", "React", "VueJS", "Angular", "Svelte"]}'
          labels-not-allowed: '["Falta de informações"]'
          default-labels: '["PDF"]'
```
